version: "3"

services:
  db_mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: db_mysql
    restart: always
    ports:
      - 3306:3306
    extra_hosts:
      - "host.docker.internal:host-gateway"

    environment:
      - USER=root
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
